-- Shared KYB dossier (legal entity, legal representative, documents, terms consent, SIRENE
-- snapshot) collected after the fast SIRET-only registration, for both artisan and repairer
-- accounts. Same column set on both tables — kept denormalized (no shared join table) since
-- each profile owns exactly one KYB dossier.

ALTER TABLE artisan_profiles
    ADD COLUMN kyb_legal_category            SMALLINT,
    ADD COLUMN kyb_business_entity           VARCHAR(255),
    ADD COLUMN kyb_vat_number                VARCHAR(50),
    ADD COLUMN kyb_address_line1             VARCHAR(255),
    ADD COLUMN kyb_address_city              VARCHAR(255),
    ADD COLUMN kyb_address_postal_code       VARCHAR(20),
    ADD COLUMN kyb_address_country           VARCHAR(2),
    ADD COLUMN kyb_terms_accepted_at         TIMESTAMPTZ,
    ADD COLUMN kyb_rep_first_name            VARCHAR(255),
    ADD COLUMN kyb_rep_last_name             VARCHAR(255),
    ADD COLUMN kyb_rep_birth_date            DATE,
    ADD COLUMN kyb_rep_nationality           VARCHAR(2),
    ADD COLUMN kyb_rep_address_line1         VARCHAR(255),
    ADD COLUMN kyb_rep_address_city          VARCHAR(255),
    ADD COLUMN kyb_rep_address_postal_code   VARCHAR(20),
    ADD COLUMN kyb_rep_address_country       VARCHAR(2),
    ADD COLUMN kyb_rep_is_ubo                BOOLEAN,
    ADD COLUMN kyb_rep_ownership_percentage  SMALLINT,
    ADD COLUMN kyb_doc_id_file_id            UUID REFERENCES files(id),
    ADD COLUMN kyb_doc_kbis_file_id          UUID REFERENCES files(id),
    ADD COLUMN kyb_doc_proof_of_address_file_id UUID REFERENCES files(id),
    ADD COLUMN kyb_doc_rib_file_id           UUID REFERENCES files(id),
    ADD COLUMN kyb_sirene_siren              VARCHAR(9),
    ADD COLUMN kyb_sirene_siege_address      VARCHAR(500),
    ADD COLUMN kyb_sirene_nature_juridique   VARCHAR(10),
    ADD COLUMN kyb_sirene_dirigeants         JSONB;

ALTER TABLE repairer_profiles
    ADD COLUMN kyb_legal_category            SMALLINT,
    ADD COLUMN kyb_business_entity           VARCHAR(255),
    ADD COLUMN kyb_vat_number                VARCHAR(50),
    ADD COLUMN kyb_address_line1             VARCHAR(255),
    ADD COLUMN kyb_address_city              VARCHAR(255),
    ADD COLUMN kyb_address_postal_code       VARCHAR(20),
    ADD COLUMN kyb_address_country           VARCHAR(2),
    ADD COLUMN kyb_terms_accepted_at         TIMESTAMPTZ,
    ADD COLUMN kyb_rep_first_name            VARCHAR(255),
    ADD COLUMN kyb_rep_last_name             VARCHAR(255),
    ADD COLUMN kyb_rep_birth_date            DATE,
    ADD COLUMN kyb_rep_nationality           VARCHAR(2),
    ADD COLUMN kyb_rep_address_line1         VARCHAR(255),
    ADD COLUMN kyb_rep_address_city          VARCHAR(255),
    ADD COLUMN kyb_rep_address_postal_code   VARCHAR(20),
    ADD COLUMN kyb_rep_address_country       VARCHAR(2),
    ADD COLUMN kyb_rep_is_ubo                BOOLEAN,
    ADD COLUMN kyb_rep_ownership_percentage  SMALLINT,
    ADD COLUMN kyb_doc_id_file_id            UUID REFERENCES files(id),
    ADD COLUMN kyb_doc_kbis_file_id          UUID REFERENCES files(id),
    ADD COLUMN kyb_doc_proof_of_address_file_id UUID REFERENCES files(id),
    ADD COLUMN kyb_doc_rib_file_id           UUID REFERENCES files(id),
    ADD COLUMN kyb_sirene_siren              VARCHAR(9),
    ADD COLUMN kyb_sirene_siege_address      VARCHAR(500),
    ADD COLUMN kyb_sirene_nature_juridique   VARCHAR(10),
    ADD COLUMN kyb_sirene_dirigeants         JSONB;
